import Head from 'next/head'
import {BsFillMoonStarsFill}  from 'react-icons/bs';
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import Image from 'next/image';
import kakarot from '../public/kakarot.jpg';
import artbox from '../public/design.jpg';
import web from '../public/web.jpg';
import web1 from '../public/web1.jpg';
import web2 from '../public/web2.jpg';
import web3 from '../public/web3.jpg';
import web4 from '../public/web4.jpg';
import web5 from '../public/web5.jpg';
import { useState } from "react";



export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div  className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' bg-white px-10 md:px-20 lg:px-40  dark:bg-gray-900'>
        <section className='mid-h-screen'>
          {/* nav bar */}
          <nav className=' py-10 mb-10 flex justify-between  dark:text-white'>
            <h1 className='test-xl font-burtons'> Rastogi</h1>
            <ul className=' flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl'/>
              </li>
              <li>
                <a className=' bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' 
              href="#">
                Resume
                </a></li>
            </ul>
          </nav>
          {/* content */}
          <div className=' text-center p-10'>
            <h2 className=' text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:text-teal-400'>
              Dhawal Rastogi</h2>
            <h3 className='text-2xl py-2 md:text-3xl'>A baka guy</h3>
            <p className=' text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-200'>
              reality, most random numbers used in computer programs 
              are pseudo-random, which means they are generated in a 
              predictable fashion using a mathematical formula. This 
              is fine for many purposes, but it may not be random in
               the way you expect if you're used to dice rolls and 
               lottery drawings.</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400'>
            <AiFillLinkedin/>
            <AiFillTwitterCircle/>
            <AiFillYoutube/>
          </div>
          {/* display pic */}
          <div className=' relative rounded-full mx-auto mt-20'>
            <Image alt='noImg' src={kakarot} className='rounded-full w-80 h-80 mx-auto md:h-98 md:w-98'/>
          </div>
        </section>

        <section>
          <div>
            <h3 className=' text-3xl py-1 dark:text-white'>services</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>
              hey yo
            </p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>
              thora or likh dena h;lmc;lam sdknosknd sdonakns aonsdkan
              knalskndklsa;ldmas; a;lsmd;lsam aklsmd;klnma 
              slkndkln
            </p>
          </div>
          {/* skill box */}
          <div className='lg:flex gap-10 '>
            <div className=' text-center shadow-lg p-10 rounded-xl my-10 flex-1 dark:bg-white'>
             <Image alt='no image' src={artbox} width={100} height={100} className='mx-auto'/>
             <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Design</h3>
             <p className='py-2'>Kawaii kawaii design</p>
             <h4 className='py-4 text-teal-600'>Tools I use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>figma</p>
              <p className='text-gray-800 py-1'>AC/DC</p>
            </div>

            <div className=' text-center shadow-lg p-10 rounded-xl my-10 flex-1 dark:bg-white'>
             <Image alt='no image' src={artbox} width={100} height={100} className='mx-auto'/>
             <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Design</h3>
             <p className='py-2'>Kawaii kawaii design</p>
             <h4 className='py-4 text-teal-600'>Tools I use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>figma</p>
              <p className='text-gray-800 py-1'>AC/DC</p>
            </div>

            <div className=' text-center shadow-lg p-10 rounded-xl my-10 flex-1 dark:bg-white'>
             <Image alt='no image' src={artbox} width={100} height={100} className='mx-auto'/>
             <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Design</h3>
             <p className='py-2'>Kawaii kawaii design</p>
             <h4 className='py-4 text-teal-600'>Tools I use</h4>
              <p className='text-gray-800 py-1'>Photoshop</p>
              <p className='text-gray-800 py-1'>figma</p>
              <p className='text-gray-800 py-1'>AC/DC</p>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'>photofolio</h3>
            <p className=' text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>some more text</p>
            <p className=' text-md py-2 leading-8 text-gray-800 dark:text-gray-200'>some u want more</p>
          </div>
          {/* images */}
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image alt='no image' src={web} className='rounded-lg object-cover'/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image alt='no image' src={web1}className='rounded-lg object-cover'/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image alt='no image' src={web2}className='rounded-lg object-cover' />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image alt='no image' src={web3}className='rounded-lg object-cover'  />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image alt='no image' src={web4}className='rounded-lg object-cover' />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image alt='no image' src={web5}className='rounded-lg object-cover' />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}